#!/usr/bin/env python3
"""
Regenerate the endpoint index for one system from its OpenAPI YAML file(s).

Run this after the spec files are updated (new release) to keep the index in
sync:

    python3 scripts/build_index.py --system core
    python3 scripts/build_index.py --system data-factory

Each system's specs live under spec/<system>/ and its index is written to
references/endpoint-index-<system>.md. The index is a compact, cheap-to-read
table of every operation (method + path + operationId + summary + tags +
source file) — NOT the full schema. Use lookup_endpoint.py against the source
file for that, so Claude never has to load an entire domain YAML file just to
answer a question about one endpoint.
"""
import argparse
import glob
import os
import sys

import yaml

ROOT = os.path.join(os.path.dirname(__file__), "..")
METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def load_spec_files(spec_dir):
    # index.yaml (core) is a pure $ref router with no operations of its own — skip it.
    return sorted(f for f in glob.glob(os.path.join(spec_dir, "*.yaml")) if os.path.basename(f) != "index.yaml")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--system", required=True, choices=["core", "data-factory"])
    args = ap.parse_args()

    spec_dir = os.path.join(ROOT, "spec", args.system)
    out_path = os.path.join(ROOT, "references", f"endpoint-index-{args.system}.md")
    files = load_spec_files(spec_dir)

    rows = []  # (file, method, path, operationId, tags, summary)
    for fpath in files:
        fname = os.path.basename(fpath)
        try:
            doc = yaml.safe_load(open(fpath, encoding="utf-8"))
        except Exception as e:
            print(f"WARNING: failed to parse {fname}: {e}", file=sys.stderr)
            continue
        paths = (doc or {}).get("paths", {}) or {}
        for path, item in paths.items():
            if not isinstance(item, dict):
                continue
            for method, op in item.items():
                if method.lower() not in METHODS or not isinstance(op, dict):
                    continue
                op_id = op.get("operationId", "")
                tags = ",".join(op.get("tags", []) or [])
                summary = (op.get("summary") or "").strip().replace("\n", " ")
                rows.append((fname, method.upper(), path, op_id, tags, summary))

    rows.sort(key=lambda r: (r[0], r[2], r[1]))

    title = "Signals Core API" if args.system == "core" else "Signals Data Factory (SDF) API"
    lines = [
        f"# {title} — Endpoint Index",
        "",
        f"Auto-generated by `scripts/build_index.py --system {args.system}` from {len(files)} spec file(s) "
        f"in `spec/{args.system}/`. {len(rows)} operations total.",
        "",
        "Find the operation you need here first (by path, operationId, or tag), note its **file**, "
        f"then run `scripts/lookup_endpoint.py --system {args.system} <file> <METHOD> <path>` to pull the "
        "full parameter/schema detail for just that operation — do not open the spec YAML file(s) directly.",
        "",
        "| File | Method | Path | operationId | Tags | Summary |",
        "|---|---|---|---|---|---|",
    ]
    for fname, method, path, op_id, tags, summary in rows:
        lines.append(f"| {fname} | {method} | `{path}` | {op_id} | {tags} | {summary} |")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path}: {len(rows)} operations across {len(files)} file(s).")


if __name__ == "__main__":
    main()
